repos:
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
   - id: black
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args:
       - --in-place
       - --remove-unused-variables
       - --remove-all-unused-imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args:
        - --line-length=88
        - --src=report_generator
        - --profile=black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: no-commit-to-branch
      args:
        - --pattern=develop|main
    - id: requirements-txt-fixer
    - id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: data
        additional_dependencies: [flake8-docstrings, flake8-fixme,flake8-pep3101]
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true